# -*- coding: utf-8 -*-
"""2REGRESION_LOGISTICA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1uMtLXHAji3OcdHbBlhHX3r0M_tXHyG

# **SEGUNDA EJECUCION: REGRESION LOGISTICA**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, roc_auc_score, RocCurveDisplay
from google.colab import drive
import matplotlib.pyplot as plt


drive.mount('/content/drive', force_remount=True)
ruta_carga = '/content/drive/MyDrive/dataset/datasetFINALFINAL1.csv'

df = pd.read_csv(ruta_carga, sep=';', decimal=',')
df.columns = df.columns.str.strip()

print("✅ Columnas cargadas:", df.columns.tolist())

X = df.drop('cardio', axis=1)
y = df['cardio']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=42, stratify=y
)

print(f"Tamaño de los datos de entrenamiento (50%): {X_train.shape[0]} registros")
print(f"Tamaño de los datos de prueba (50%): {X_test.shape[0]} registros")

modelo_pipeline = Pipeline(steps=[
    ('classifier', LogisticRegression(
        solver='liblinear',
        random_state=42,
        class_weight='balanced'
    ))
])

# Entrenar el modelo
modelo_pipeline.fit(X_train, y_train)
print("✅ Modelo entrenado exitosamente.")

# Predecir probabilidades
y_prob = modelo_pipeline.predict_proba(X_test)[:, 1]

threshold = 0.4
y_pred_adj = (y_prob >= threshold).astype(int)

# Metricas de evaluacion
accuracy = accuracy_score(y_test, y_pred_adj)
recall = recall_score(y_test, y_pred_adj)
f1 = f1_score(y_test, y_pred_adj)
roc_auc = roc_auc_score(y_test, y_prob)

print("\n--- 📝 Metricas del modelo (50/50) ---")
print(f"Threshold: {threshold}")
print(f"Accuracy: {accuracy:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

# Matriz de Confusion
matriz = confusion_matrix(y_test, y_pred_adj)
df_matriz = pd.DataFrame(
    matriz,
    index=['Real: No ECV (0)', 'Real: Si ECV (1)'],
    columns=['Predicción: No ECV (0)', 'Predicción: Si ECV (1)']
)

print("\n--- 🧮 Matriz de Confusion (50/50) ---")
print(df_matriz)

# Curva de ROC
RocCurveDisplay.from_estimator(modelo_pipeline, X_test, y_test)
plt.title("Curva ROC - Segunda Ejecucion (50/50)")
plt.show()